from typing import Protocol, Iterable, Optional
from Turismo.domain.models import Pacote

class PacoteRepository(Protocol):
    def add(self, pacote: Pacote) -> None: ...
    def get_by_id(self, id_: int) -> Optional[Pacote]: ...
    def list_all(self) -> Iterable[Pacote]: ...
    def update(self, pacote: Pacote) -> None: ...
    def delete(self, id_: int) -> None: ...